# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x0f\x66leet.telemetry\"\x89\x03\n\x10VehicleTelemetry\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x11\n\tspeed_kmh\x18\x05 \x01(\x01\x12\x0b\n\x03rpm\x18\x06 \x01(\x05\x12\x14\n\x0cthrottle_pct\x18\x07 \x01(\x01\x12\x15\n\rfuel_flow_lph\x18\x08 \x01(\x01\x12\x13\n\x0b\x62rake_event\x18\t \x01(\x08\x12\x17\n\x0f\x62rake_force_pct\x18\n \x01(\x01\x12\x1a\n\x12\x62raking_distance_m\x18\x0b \x01(\x01\x12\x18\n\x10\x61\x63\x63\x65leration_ms2\x18\x0c \x01(\x01\x12\x16\n\x0eload_weight_kg\x18\r \x01(\x01\x12\x15\n\rengine_temp_c\x18\x0e \x01(\x01\x12\x1a\n\x12idle_duration_secs\x18\x0f \x01(\x05\x12\x15\n\rgear_position\x18\x10 \x01(\t\x12\x16\n\x0eroad_grade_pct\x18\x11 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLETELEMETRY._serialized_start=34
  _VEHICLETELEMETRY._serialized_end=427
# @@protoc_insertion_point(module_scope)
